Repository Team-Ampersand/DUS, pull requests merged in 2023-09, with the labels that each got.

#67 🚀 :: DUS 1.0.2 release
  buildSrc/src/main/java/ProjectProperties.kt
Labels: 🌏 Type: Deploy, 0️⃣ Priority: Critical

#69 🔀 :: (#68) modify for dotori text field
  dotori-components/src/main/java/com/dotori/dotori_components/components/text_field/TextField.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/utils/Types.kt
Labels: 1️⃣ Priority: High, 🔨 Type: Refector

#70 🚀 :: 1.0.4 업데이트
  dotori-components/src/main/java/com/dotori/dotori_components/components/text_field/TextField.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/utils/Types.kt
  dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriIcon.kt
Labels: 1️⃣ Priority: High, 🌏 Type: Deploy

#73 🚀 :: 1.0.5 업데이트
  dotori-components/src/main/java/com/dotori/dotori_components/components/bottomsheet/BottomSheetDialog.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#75 🔀 :: (#74) dotori bottom sheet null value exception
  buildSrc/src/main/java/Versions.kt
Labels: 🐞 Type: Bug, 0️⃣ Priority: Critical

#76 🚀 :: 1.0.6 업데이트
  buildSrc/src/main/java/Versions.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#79 🔀 :: (#78) add skip half expanded to bottom sheet dialog
  dotori-components/src/main/java/com/dotori/dotori_components/components/bottomsheet/BottomSheetDialog.kt
Labels: ✨ Type: Feature, 0️⃣ Priority: Critical

#81 🔀 :: (#80) add on day selected parameter to calendar
  buildSrc/src/main/java/ProjectProperties.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/calendar/DotoriCalendar.kt
Labels: ✨ Type: Feature, 0️⃣ Priority: Critical

#82 🔀 :: (#77) doroti button에 padding values 추가
  dotori-components/src/main/java/com/dotori/dotori_components/components/button/DotoriButton.kt
Labels: 2️⃣ Priortiy: Medium, ⚡Type: Simple

#84 🚀 :: 1.0.7 업데이트
  buildSrc/src/main/java/ProjectProperties.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/bottomsheet/BottomSheetDialog.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/button/DotoriButton.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/calendar/DotoriCalendar.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#86 🔀 :: (#85) dotori bottom sheet modal exception
  buildSrc/src/main/java/Versions.kt
Labels: 🐞 Type: Bug, 0️⃣ Priority: Critical

#87 🚀 :: 1.0.8 업데이트
  buildSrc/src/main/java/Versions.kt
Labels: 🐞 Type: Bug, 0️⃣ Priority: Critical

#89 🔀 :: (#88) dotori button text style 변경 가능하게 수정
  dotori-components/src/main/java/com/dotori/dotori_components/components/button/DotoriButton.kt
Labels: 2️⃣ Priortiy: Medium, ⚡Type: Simple

#90 🚀 :: 1.0.9 업데이트
  dotori-components/src/main/java/com/dotori/dotori_components/components/button/DotoriButton.kt
Labels: 🌏 Type: Deploy, 0️⃣ Priority: Critical

#92 🔀 :: (#91) - implement the dotori watch
  dotori-components/src/main/java/com/dotori/dotori_components/components/watch/DotoriWatch.kt
  dotori-components/src/main/res/drawable/bg_dotori_watch.xml
  dotori-components/src/main/res/drawable/img_dark_dotori.png
  dotori-components/src/main/res/drawable/img_white_dotori.png
Labels: enhancement, 0️⃣ Priority: Critical

#95 🔀 :: (#94) modify dotori student info list item click event
  dotori-components/src/main/java/com/dotori/dotori_components/components/student_info/DotoriStudentInfoListItem.kt
Labels: 1️⃣ Priority: High, 🐞 Type: Bug

#97 🚀 :: 1.0.11 업데이트
  dotori-components/src/main/java/com/dotori/dotori_components/components/student_info/DotoriStudentInfoListItem.kt
Labels: 🌏 Type: Deploy, 0️⃣ Priority: Critical

#99 🔀 :: (#98) modify dotori role violate list item click event
  dotori-components/src/main/java/com/dotori/dotori_components/components/rule/DotoriRoleViolateListItem.kt
Labels: 1️⃣ Priority: High, 🐞 Type: Bug

#102 🔀 :: (#101) 1.0.13 업데이트
  dotori-components/src/main/java/com/dotori/dotori_components/components/rule/DotoriRoleViolateListItem.kt
Labels: 1️⃣ Priority: High, 🌏 Type: Deploy

#104 🔀 :: (#103) doroti button 수정
  dotori-components/src/main/java/com/dotori/dotori_components/components/button/DotoriButton.kt
Labels: ✨ Type: Feature, 0️⃣ Priority: Critical

#106 🔀 :: (#106) 1.0.16 출시
  dotori-components/src/main/java/com/dotori/dotori_components/components/button/DotoriButton.kt
Labels: 1️⃣ Priority: High, 🌏 Type: Deploy

#108 🔀 :: (#107) modify check student card role
  dotori-components/src/main/java/com/dotori/dotori_components/components/card/DotoriCard.kt
Labels: 2️⃣ Priortiy: Medium, ⚡Type: Simple

#110 1.0.17 출시
  dotori-components/src/main/java/com/dotori/dotori_components/components/card/DotoriCard.kt
Labels: 1️⃣ Priority: High, 🌏 Type: Deploy

#112 🔀 :: (#111) button customable items
  dotori-components/src/main/java/com/dotori/dotori_components/components/button/DotoriButton.kt
Labels: 2️⃣ Priortiy: Medium, ⚡Type: Simple

#114 🔀 :: (#113) modifier dotori notice list item
  dotori-components/src/main/java/com/dotori/dotori_components/components/notice/DotoriNoticeListItem.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#115 1.0.18 업데이트
  dotori-components/src/main/java/com/dotori/dotori_components/components/button/DotoriButton.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/notice/DotoriNoticeListItem.kt
Labels: 1️⃣ Priority: High, 🌏 Type: Deploy

#117 🔀 :: (#116) modify body1 line height
  dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriTypography.kt
Labels: 🐞 Type: Bug, 0️⃣ Priority: Critical

#118 1.0.19 업데이트
  dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriTypography.kt
Labels: 🌏 Type: Deploy, 0️⃣ Priority: Critical

#120 🔀 :: (#119) - insert the icons on meal component
  dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriIcon.kt
  dotori-components/src/main/res/drawable/ic_chevron_left.xml
  dotori-components/src/main/res/drawable/ic_chevron_right.xml
Labels: ✨ Type: Feature, 0️⃣ Priority: Critical
