Repository Team-Ampersand/DUS, pull requests merged in 2023-08, with the labels that each got.

#29 🔀 :: (#28) - dotori checkbox design system
  dotori-components/src/main/java/com/dotori/dotori_components/components/checkbox/DotoriCheckBox.kt
  dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriIcon.kt
  dotori-components/src/main/res/drawable/ic_check.xml
Labels: enhancement, feature

#32 🔀 :: (#30) create segmented buttons
  dotori-components/src/main/java/com/dotori/dotori_components/components/button/SegmentedButtons.kt
Labels: enhancement, feature

#33 🔀 :: (#30) implement calendar component
  dotori-components/src/main/java/com/dotori/dotori_components/components/calendar/CalendarDayItem.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/calendar/CalendarHeader.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/calendar/CalendarWeekBar.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/calendar/DotoriCalendar.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/calendar/util/CalendarUtil.kt
Labels: enhancement, feature

#35 🔀 :: (#34) toggle component 생성
  dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/Switch.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/toggle/ThemeSwitch.kt
Labels: enhancement, feature

#37 🔀 :: (#36) drop down menu component 생성
  dotori-components/src/main/java/com/dotori/dotori_components/components/menu/DotoriDropDownMenu.kt
Labels: enhancement, feature

#39 🔀 :: (#38) student card component checkbox 추가
  dotori-components/src/main/java/com/dotori/dotori_components/components/card/DotoriCard.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/utils/Types.kt
Labels: enhancement, feature

#41 🔀 :: (#40) button 로직 변경
  dotori-components/src/main/java/com/dotori/dotori_components/components/button/DotoriButton.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/card/DotoriMainCard.kt
Labels: 1️⃣ Priority: High, ⚡Type: Simple

#44 🔀 :: (#42) add notice list item
  dotori-components/src/main/java/com/dotori/dotori_components/components/notice/DotoriNoticeListItem.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#47 🔀 :: (#45) role badge, self study icon 생성
  dotori-components/src/main/java/com/dotori/dotori_components/components/role/DotoriRoleBadge.kt
  dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriIcon.kt
  dotori-components/src/main/res/drawable/ic_self_study_allow.xml
  dotori-components/src/main/res/drawable/ic_self_study_disallow.xml
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#46 🔀 :: (#43) music list item
  dotori-components/src/main/java/com/dotori/dotori_components/components/music/DotoriMusicListItem.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#49 🔀 :: (#48) main card 수정
  dotori-components/src/main/java/com/dotori/dotori_components/components/card/DotoriMainCard.kt
  dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriIcon.kt
  dotori-components/src/main/res/drawable/ic_arrow_right2.xml
  dotori-components/src/main/res/drawable/ic_refresh_icon.xml
  dotori-components/src/main/res/drawable/ic_setting_icon.xml
Labels: 1️⃣ Priority: High, ⚡Type: Simple

#53 🔀 :: (#50) add student info list item
  dotori-components/src/main/java/com/dotori/dotori_components/components/student_info/DotoriStudentInfoListItem.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#54 🔀 :: (#52) change meatball icon color
  dotori-components/src/main/java/com/dotori/dotori_components/components/music/DotoriMusicListItem.kt
Labels: 1️⃣ Priority: High, ⚡Type: Simple

#56 🔀 :: (#51) rule violation item
  dotori-components/src/main/java/com/dotori/dotori_components/components/rule/DotoriRoleViolateItem.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/utils/RoleViolateType.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#58 🔀 :: (#55) add role violate list item
  dotori-components/src/main/java/com/dotori/dotori_components/components/rule/DotoriRoleViolateListItem.kt
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#59 🔀 :: (#57) create issue, pr templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 1️⃣ Priority: High, 📄 Type: Docs

#61 🔀 :: (#60) add bottom navigate bar
  dotori-components/src/main/java/com/dotori/dotori_components/components/bottom_navigate_bar/DotoriNavBar.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/bottom_navigate_bar/DotoriNavBarItem.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/bottom_navigate_bar/DotoriNavBarItemType.kt
  dotori-components/src/main/java/com/dotori/dotori_components/components/button/DotoriSegmentedButtons.kt
  dotori-components/src/main/java/com/dotori/dotori_components/theme/DotoriIcon.kt
  dotori-components/src/main/res/drawable/ic_home.xml
  dotori-components/src/main/res/drawable/ic_massage_chair.xml
  dotori-components/src/main/res/drawable/ic_notice_bell.xml
  dotori-components/src/main/res/drawable/ic_pressed_home.xml
  dotori-components/src/main/res/drawable/ic_pressed_massage_chair.xml
  dotori-components/src/main/res/drawable/ic_pressed_notice_bell.xml
  dotori-components/src/main/res/drawable/ic_pressed_self_study.xml
  dotori-components/src/main/res/drawable/ic_pressed_wake_up_music.xml
  dotori-components/src/main/res/drawable/ic_self_study.xml
  dotori-components/src/main/res/drawable/ic_wake_up_music.xml
Labels: 1️⃣ Priority: High, ✨ Type: Feature

#63 🔀 :: (#62) setting maven gradle plugin and release
  build.gradle.kts
  buildSrc/src/main/java/Dependency.kt
  buildSrc/src/main/java/Plugins.kt
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  dotori-components/build.gradle.kts
Labels: 1️⃣ Priority: High, 🌏 Type: Deploy

#66 🔀 :: (#65) Jitpack 1.0.0 에러 수정
  buildSrc/src/main/java/ProjectProperties.kt
  buildSrc/src/main/java/Versions.kt
  jitpack.yml
Labels: 🌏 Type: Deploy, 0️⃣ Priority: Critical
